name: CI/CD Blue-Green Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPO: <YOUR_ECR_REPO_NAME>
  DOCKER_IMAGE: ${{ env.ECR_REPO }}:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin <ACCOUNT_ID>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE }} -f docker/Dockerfile .

    - name: Push Docker image to ECR
      run: docker push ${{ env.DOCKER_IMAGE }}

    - name: Deploy to AWS (Blue-Green)
      run: |
        ALB_ARN=$(aws elbv2 describe-load-balancers --names blue-green-alb --query "LoadBalancers[0].LoadBalancerArn" --output text)
        BLUE_TG_ARN=$(aws elbv2 describe-target-groups --names app-blue --query "TargetGroups[0].TargetGroupArn" --output text)
        GREEN_TG_ARN=$(aws elbv2 describe-target-groups --names app-green --query "TargetGroups[0].TargetGroupArn" --output text)
        bash scripts/deploy.sh $ALB_ARN $BLUE_TG_ARN $GREEN_TG_ARN ${{ env.DOCKER_IMAGE }}
